# Get Me
GET http://localhost:8899/api/auth/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzgwNzI3NTU3LCJleHAiOjE3ODIwMjM1NTd9.uzjO-ziC2XQFPMHX2G8nFntfvuzNMLWT7Cfy0kjSzZ0
###


GET http://localhost:8899/api/reg

###
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
 "identity" : "friend@mail.com",
 "password" : "123456"
}

### Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
#  "identity" : "1234567890",
 "identity" : "friend@mail.com",
 "firstName" : "friend",
 "lastName" : "codecamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}
###


###
POST http://localhost:8899/api/post HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzgwNzI3NTU3LCJleHAiOjE3ODIwMjM1NTd9.uzjO-ziC2XQFPMHX2G8nFntfvuzNMLWT7Cfy0kjSzZ0
content-type: application/json

{
   "message": "sample"
}
